### PR TITLE
In case of embed view and if Location is passed in, use eZ Location

### PR DESCRIPTION
**Pull request by MarioBlazek**

### CODE REVIEW

**Comment by emodric** [comment]
Can you explain why, for me and for future reference? :)

**Comment by emodric** [comment]
Also  don't we have some embed views in site bundle which use site api location, which would potentially break here?

**Comment by hknezevic** [comment]
@emodric seems that this happens only in case when you render the embed view for the content explicitly in the template ( render(controller('ngContent:viewAction') ), and only if you explicitly pass the locationId or location parameter to it. 

If the embed template is invoked the regular way (from the rich text ), then this will not happen, since only the content is passed on. The authorization checker for the location is invoked only if the location is passed explicitly to the embed view.

**Comment by MarioBlazek** [comment]
@emodric this was an exceptional case when `embed` view was rendered and also location was passed as a parameter:

```twig
    {{ render(
        controller(
              'ng_content:viewAction', {
                    'contentId': content.id,
                    'locationId': location.id,
                    'viewType': 'embed'
               }
         )
     ) }}
```

**Comment by hknezevic** [comment]
@emodric the authorization checker expects input argument to be either an instance of the eZ core Location or SPILocation

**Comment by emodric** [comment]
Okay, will it mess up the outer context since this modifies a variable which is passed by reference?

**Comment by pspanja** [comment]
@emodric 

> Okay, will it mess up the outer context since this modifies a variable which is passed by reference?

Actually it won't. It would happen if the object was being passed by reference, which it isn't.

Edit: explicitly passed by reference. PHP is weird :)

**Review by pspanja — CHANGES_REQUESTED** [review]
Looks good, but I would still not overwrite method's argument. We can introduce a new variable, `$innerLocation` or `$repositoryLocation` and use it instead.

**Comment by emodric** [comment]
Aren't objects passed by reference by default?

**Comment by pspanja** [comment]
Kind of :) See https://3v4l.org/iMHCl

**Comment by emodric** [comment]
I see. Good to know :+1:

**Comment by hknezevic** [comment]
@MarioBlazek this looks better ;)

**Comment by MarioBlazek** [comment]
@emodric @pspanja objects are passed as references in methods, not in functions. In functions this needs to be done explicitly.

**Comment by MarioBlazek** [comment]
Thanks for pinpointing the potential issue.

**Comment by emodric** [comment]
@MarioBlazek So the previous code would definitely break then?

**Review by pspanja — APPROVED** [review]

**Comment by pspanja** [comment]
Thanks @MarioBlazek!

**Comment by pspanja** [comment]
> So the previous code would definitely break then?

It would not break. Behavior is the same in both functions and methods.

**Comment by emodric** [comment]
@MarioBlazek @pspanja Fight, fight! :)

**Comment by pspanja** [comment]
There's really nothing to fight about, it works the way it works :)

**Pull request merged**
