### PR TITLE
The alias for ezpublish.controller.content.preview must indicate that…

### PR DESCRIPTION
**Pull request by YohannsMonnier**
… this service is public, as it is in the overrided definition

This is a proposed fix.

### CODE REVIEW

**Comment by emodric** [comment]
As commented in https://github.com/netgen/ezplatform-site-api/issues/167 , we really don't need that line in `4.0`. So you can just remove it (and rebase this PR to `4.0` as it can stay as it is in 3.x)?

**Comment by YohannsMonnier** [comment]
@emodric , ok it is done !

**Comment by emodric** [comment]
Thanks :) Please rebase to 4.0 to remove extra commits, and we can merge (you only changed base on github, but you sti need rebase)

**Comment by YohannsMonnier** [comment]
@emodric I did the following on my repo : 

**git rebase origin/4.0**
  On branch fix/service-content-preview-override-ezp3.X
Your branch and 'origin/fix/service-content-preview-override-ezp3.X' have diverged,
and have 20 and 4 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
**git pull**
   Merge made by the 'recursive' strategy.
**git status**
    On branch fix/service-content-preview-override-ezp3.X
Your branch is ahead of 'origin/fix/service-content-preview-override-ezp3.X' by 21 commits.
  (use "git push" to publish your local commits)
** git push**
Enumerating objects: 37, done.
Counting objects: 100% (37/37), done.
Delta compression using up to 8 threads
Compressing objects: 100% (21/21), done.
Writing objects: 100% (21/21), 2.01 KiB | 2.01 MiB/s, done.
Total 21 (delta 17), reused 0 (delta 0)
remote: Resolving deltas: 100% (17/17), completed with 8 local objects.
To https://github.com/YohannsMonnier/ezplatform-site-api.git
   0d8d3c4..8b4d827  fix/service-content-preview-override-ezp3.X -> fix/service-content-preview-override-ezp3.X

**Comment by emodric** [comment]
Hm, still looks wrong :/

I will merge manually tomorrow morning! 👍

**Comment by emodric** [comment]
Merged manually in 89bf76e08505a44158c3cc543ed37d87655333fc

Thanks @YohannsMonnier !

**Comment by YohannsMonnier** [comment]
Dear @emodric when deleting this line from live version of your bundle in a eZPlatfrom v3.1 project, I got this : 
`The definition for "ezpublish.controller.content.preview" has no class. If you intend to inject this service dynamically at runtime, please mark it as synthetic=true. If this is an abstract definition solely used by child definitions, please add abstract=true, otherwise specify a class to get rid of this error.
`

**Comment by emodric** [comment]
@YohannsMonnier Did you clear all the caches after removing the line?

I have tested the preview controller in eZ admin and it is working as expected.

**Comment by YohannsMonnier** [comment]
We have cleaned the cache, then test it in another instal and still have the same error  

`Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In CheckDefinitionValidityPass.php line 59:
!!                                                                                 
!!    The definition for "ezpublish.controller.content.preview" has no class. If   
!!    you intend to inject this service dynamically at runtime, please mark it as  
!!     synthetic=true. If this is an abstract definition solely used by child def  
!!    initions, please add abstract=true, otherwise specify a class to get rid of  
!!     this error.                                                                 
!!                                                                                 
!!  
!!  `

**Comment by emodric** [comment]
Have you checked your code now that it doesn't do anything weird? I have tested the preview controller again and it works fine after your PR.

**Comment by YohannsMonnier** [comment]
Did you test it against ezp3.1 ?

Yohann

**Comment by emodric** [comment]
Yes, using https://github.com/netgen/media-site/tree/ezplatform3

**Comment by YohannsMonnier** [comment]
@emodric is this version you are talking about working with the page builder ? The difference I could see is that our project use the eZ3.1 version EE.

**Comment by emodric** [comment]
That one is open source, so no page builder. But, I don't see a reason why it shouldn't work on enterprise version too.

**Comment by YohannsMonnier** [comment]
I don't know why it's different, would it break your version if you re-add this code inside the 4.0 branch ?
in the head :
`use Symfony\Component\DependencyInjection\Alias;`
in the function : 
`// Resetting the alias to the original value
        // to disable legacy bridge taking over the preview controller
        $container->setAlias(
            'ezpublish.controller.content.preview',
            new Alias($corePreviewControllerServiceId, true)
        );`

**Comment by emodric** [comment]
@pspanja WDYT? Any tips?

**Comment by pspanja** [comment]
@YohannsMonnier that fixes the issue?

I looked a bit into the container to find out how this could make a difference, but could not find any clues. I'll test it a bit more tomorrow. Is there maybe anything else in your codebase modifying `ezpublish.controller.content.preview` service?

**Comment by pspanja** [comment]
@YohannsMonnier Please check what you get back when executing:

```console
php bin/console debug:container ezpublish.controller.content.preview
php bin/console debug:container ezpublish.controller.content.preview.core
```

Both with and without the added alias.

**Comment by YohannsMonnier** [comment]
Dear @pspanja and @emodric , thank you to take time for this problem

**With alias :** 
` ~/ez sfrun "debug:container ezpublish.controller.content.preview"

 // This service is a public alias for the service ezpublish.controller.content.preview.core

Information for Service "ezpublish.controller.content.preview.core"
===================================================================

 ---------------- --------------------------------------------------------------------
  Option           Value
 ---------------- --------------------------------------------------------------------
  Service ID       ezpublish.controller.content.preview.core
  Class            Netgen\Bundle\EzPlatformSiteApiBundle\Controller\PreviewController
  Tags             controller.service_arguments
  Calls            setConfigResolver, setSite
  Public           yes
  Synthetic        no
  Lazy             no
  Shared           yes
  Abstract         no
  Autowired        no
  Autoconfigured   no
 ---------------- --------------------------------------------------------------------`

`~/ez sfrun "debug:container ezpublish.controller.content.preview.core"

Information for Service "ezpublish.controller.content.preview.core"
===================================================================

 ---------------- --------------------------------------------------------------------
  Option           Value
 ---------------- --------------------------------------------------------------------
  Service ID       ezpublish.controller.content.preview.core
  Class            Netgen\Bundle\EzPlatformSiteApiBundle\Controller\PreviewController
  Tags             controller.service_arguments
  Calls            setConfigResolver, setSite
  Public           yes
  Synthetic        no
  Lazy             no
  Shared           yes
  Abstract         no
  Autowired        no
  Autoconfigured   no
 ---------------- --------------------------------------------------------------------`

**Without alias :** 

` ~/ez sfrun "debug:container ezpublish.controller.content.preview"

In CheckDefinitionValidityPass.php line 59:

  The definition for "ezpublish.controller.content.preview" has no class. If you intend to inject this service dynamically at runtime, please mark it as synthetic=true. If thi
  s is an abstract definition solely used by child definitions, please add abstract=true, otherwise specify a class to get rid of this error.



In Process.php line 254:

  The command "docker-compose -p monacoEzplatform3x -f /Users/yohann/projects/clones/monaco-ez-platform-v3.x/provisioning/dev/docker-compose.yml -f /Users/yohann/projects/clon
  es/monaco-ez-platform-v3.x/provisioning/dev/docker-compose-osx.yml exec --user www-data engine /var/www/html/project/ezplatform/bin/console debug:container ezpublish.control
  ler.content.preview" failed.

  Exit Code: 1(General error)

  Working directory: /Users/yohann/projects/clones/monaco-ez-platform-v3.x

  Output:
  ================


  Error Output:
  ================


docker:sfrun [-env|--env ENV] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-c|--config CONFIG] [--] <command> [<sfcommand>...]
`

` ~/ez sfrun "debug:container ezpublish.controller.content.preview.core"

In CheckDefinitionValidityPass.php line 59:

  The definition for "ezpublish.controller.content.preview" has no class. If you intend to inject this service dynamically at runtime, please mark it as synthetic=true. If thi
  s is an abstract definition solely used by child definitions, please add abstract=true, otherwise specify a class to get rid of this error.



In Process.php line 254:

  The command "docker-compose -p monacoEzplatform3x -f /Users/yohann/projects/clones/monaco-ez-platform-v3.x/provisioning/dev/docker-compose.yml -f /Users/yohann/projects/clon
  es/monaco-ez-platform-v3.x/provisioning/dev/docker-compose-osx.yml exec --user www-data engine /var/www/html/project/ezplatform/bin/console debug:container ezpublish.control
  ler.content.preview.core" failed.

  Exit Code: 1(General error)

  Working directory: /Users/yohann/projects/clones/monaco-ez-platform-v3.x

  Output:
  ================


  Error Output:
  ================


docker:sfrun [-env|--env ENV] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-c|--config CONFIG] [--] <command> [<sfcommand>...]`

**Comment by pspanja** [comment]
Thanks! This does not happen on my installation, so you probably have some additional logic affecting this service, either  in the project or in the vendor code, since you do use enterprise edition.

This fix does not look like it would cause any problems, but I would still want to get to the bottom of this issue. Can you please paste the result of `composer info` here, so we can see what exactly is installed in your case.

**Comment by YohannsMonnier** [comment]
~/ez comprun "info"
babdev/pagerfanta-bundle                           v2.5.0            Bundle integrating Pagerfanta with Symfony
behat/behat                                        v3.7.0            Scenario-oriented BDD framework for PHP 5.3
behat/gherkin                                      v4.6.2            Gherkin DSL parser for PHP 5.3
behat/mink-goutte-driver                           v1.2.1            Goutte driver for Mink framework
behat/mink-selenium2-driver                        v1.4.0            Selenium2 (WebDriver) driver for Mink framework
behat/transliterator                               v1.3.0            String transliterator
bex/behat-extension-driver-locator                 2.0.1             Driver locator tool for behat extensions
bex/behat-screenshot                               2.1.0             Extension for behat to help debug failing scenarios
cloudinary/cloudinary_php                          1.17.0            Cloudinary PHP SDK
clue/stream-filter                                 v1.4.1            A simple and modern approach to stream filtering in PHP
cron/cron                                          1.4.2             Cronjobs
dmore/behat-chrome-extension                       1.3.0             Behat extension for controlling chrome without selenium
dmore/chrome-mink-driver                           2.7.0             Mink driver for controlling chrome without selenium
doctrine/annotations                               1.10.3            Docblock Annotations Parser
doctrine/cache                                     1.10.2            PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such a...
doctrine/collections                               1.6.7             PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/common                                    2.13.3            PHP Doctrine Common project is a library that provides additional functionality that other Doctrine proj...
doctrine/dbal                                      2.10.2            Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and ...
doctrine/doctrine-bundle                           2.1.0             Symfony DoctrineBundle
doctrine/doctrine-migrations-bundle                3.0.1             Symfony DoctrineMigrationsBundle
doctrine/event-manager                             1.1.1             The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctr...
doctrine/inflector                                 1.4.3             PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/low...
doctrine/instantiator                              1.3.1             A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                                     1.2.1             PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                                3.0.1             PHP Doctrine Migrations project offer additional functionality on top of the database abstraction layer ...
doctrine/orm                                       v2.7.3            Object-Relational-Mapper for PHP
doctrine/persistence                               1.3.8             The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doct...
doctrine/reflection                                1.2.1             The Doctrine Reflection project is a simple library used by the various Doctrine projects which adds som...
doctrine/sql-formatter                             1.1.1             a PHP SQL highlighting library
egulias/email-validator                            2.1.18            A library for validating emails against several RFCs
elasticsearch/elasticsearch                        v7.8.0            PHP Client for Elasticsearch
erusev/parsedown                                   1.7.4             Parser for Markdown.
ezimuel/guzzlestreams                              3.0.1             Fork of guzzle/streams (abandoned) to be used with elasticsearch-php
ezimuel/ringphp                                    1.1.2             Fork of guzzle/RingPHP (abandoned) to be used with elasticsearch-php
ezplatform-i18n/ezplatform-i18n-fr_fr              v3.0.0            eZ Platform fr_FR translations
ezsystems/allure-behat                             v3.1.2            Behat output formatter for use with Yandex Allure reporting tool
ezsystems/allure-php-api                           v3.1.2            PHP API for Allure adapter
ezsystems/behat-screenshot-image-driver-cloudinary v1.1.1            Cloudinary image driver for bex/behat-screenshot behat extension
ezsystems/behatbundle                              v8.1.1            Behat bundle for help testing eZ Bundles and projects
ezsystems/date-based-publisher                     v4.1.0            Date-based Publisher bundle
ezsystems/diff                                     3.1.0             Diff implementation
ezsystems/doctrine-dbal-schema                     v1.0.0            Abstraction layer, on top of Doctrine, for cross-DBMS schema import
ezsystems/ez-support-tools                         v2.1.0            Providing information about the system eZ Platform/Enterprise/Commerce is running on, and eZ install itself
ezsystems/ezplatform-admin-ui                      v2.1.1            eZ Platform Admin v2
ezsystems/ezplatform-admin-ui-assets               v5.1.0            External assets dependencies for EzPlatform AdminUI
ezsystems/ezplatform-calendar                      v1.1.0            eZ Platform Calendar
ezsystems/ezplatform-content-forms                 v1.1.0            Use Symfony Forms with eZ Platform Content & User objects
ezsystems/ezplatform-core                          v2.1.1            eZ Platform core bundles container
ezsystems/ezplatform-cron                          v3.0.1            Simple cron bundle for eZ Platform
ezsystems/ezplatform-design-engine                 v3.0.0            Design fallback mechanism for eZ Platform
ezsystems/ezplatform-ee-installer                  v3.1.0            Installer for eZ Platform Enterprise Edition
ezsystems/ezplatform-elastic-search-engine         v1.0.0
ezsystems/ezplatform-form-builder                  v2.1.0            eZ Platform Form Builder
ezsystems/ezplatform-graphql                       v2.1.0            GraphQL server for the eZ Platform Open Source CMS Repository.
ezsystems/ezplatform-http-cache                    v2.1.0            HTTP cache handling for eZ Platform.
ezsystems/ezplatform-http-cache-fastly             v2.0.0            Fastly HTTP cache handling for eZ Platform.
ezsystems/ezplatform-kernel                        v1.1.1            Kernel used by ezsystems/ezplatform and derivatives. Provides the Content Repository, its APIs, and the ...
ezsystems/ezplatform-matrix-fieldtype              v2.0.0            Repository dedicated to Matrix Field Type for eZ Platform
ezsystems/ezplatform-page-builder                  v2.1.1            eZ Platform Page Builder
ezsystems/ezplatform-page-fieldtype                v2.1.1            eZ Platform Page FieldType
ezsystems/ezplatform-permissions                   v1.0.0
ezsystems/ezplatform-query-fieldtype               v2.1.0            An eZ Platform Field Type that defines a query.
ezsystems/ezplatform-rest                          v1.1.0            eZ Platform REST bundle
ezsystems/ezplatform-richtext                      v2.1.0            eZ Platform RichText Extension, including the RichText FieldType.
ezsystems/ezplatform-search                        v1.0.1            Platform Search bundle
ezsystems/ezplatform-site-factory                  v1.1.0            eZ Platform Site Factory bundle
ezsystems/ezplatform-solr-search-engine            v3.1.1            Solr search engine implementation for eZ Platform
ezsystems/ezplatform-standard-design               v0.3.0            eZ Platform Standard Design Bundle
ezsystems/ezplatform-user                          v2.1.0            eZ Platform User bundle
ezsystems/ezplatform-version-comparison            v1.1.0            eZ Platform Version Comparison bundle
ezsystems/ezplatform-workflow                      v2.1.0            Workflow bundle for eZ Platform Enterprise Edition
fabpot/goutte                                      v3.3.0            A simple PHP Web Scraper
friends-of-behat/mink                              v1.8.0            Browser controller/emulator abstraction for PHP
friends-of-behat/mink-browserkit-driver            v1.4.0            Symfony2 BrowserKit driver for Mink framework
friends-of-behat/mink-extension                    v2.4.0            Mink extension for Behat
friends-of-behat/symfony-extension                 v2.1.0            Integrates Behat with Symfony.
friendsofsymfony/http-cache                        2.9.2             Tools to manage HTTP caching proxies with PHP
friendsofsymfony/http-cache-bundle                 2.8.0             Set path based HTTP cache headers and send invalidation requests to your HTTP cache
friendsofsymfony/jsrouting-bundle                  2.6.0             A pretty nice way to expose your Symfony2 routing to client applications.
fzaninotto/faker                                   v1.9.1            Faker is a PHP library that generates fake data for you.
gregwar/captcha                                    v1.1.8            Captcha generator
gregwar/captcha-bundle                             v2.1.3            Captcha bundle
guzzlehttp/guzzle                                  6.5.5             Guzzle is a PHP HTTP client library
guzzlehttp/promises                                v1.3.1            Guzzle promises library
guzzlehttp/psr7                                    1.6.1             PSR-7 message implementation that also provides common utility methods
hautelook/templated-uri-bundle                     3.3.1             Symfony2 Bundle that provides a RFC-6570 compatible router and URL Generator.
hautelook/templated-uri-router                     3.3.0             Symfony2 RFC-6570 compatible router and URL Generator
imagine/imagine                                    1.2.3             Image processing for PHP 5.3
instaclick/php-webdriver                           1.4.7             PHP WebDriver for Selenium 2
jms/metadata                                       2.3.0             Class/method/property metadata management in PHP
jms/serializer                                     3.8.0             Library for (de-)serializing data of any complexity; supports XML, JSON, and YAML.
jms/translation-bundle                             1.5.4             Puts the Symfony Translation Component on steroids
knplabs/knp-menu                                   v3.1.1            An object oriented menu library
knplabs/knp-menu-bundle                            v3.0.0            This bundle provides an integration of the KnpMenu library
laminas/laminas-code                               3.4.1             Extensions to the PHP Reflection API, static code scanning, and code generation
laminas/laminas-eventmanager                       3.2.1             Trigger and listen to events within a PHP application
laminas/laminas-zendframework-bridge               1.0.4             Alias legacy ZF class names to Laminas Project equivalents.
lcobucci/jwt                                       3.3.2             A simple library to work with JSON Web Token and JSON Web Signature
league/flysystem                                   1.0.70            Filesystem abstraction: Many filesystems, one API.
lexik/jwt-authentication-bundle                    v2.8.0            This bundle provides JWT authentication for your Symfony REST API
liip/imagine-bundle                                2.3.1             This bundle provides an image manipulation abstraction toolkit for Symfony-based projects.
liuggio/fastest                                    v1.7.0            Simple parallel testing execution... with some goodies for functional tests.
lolautruche/ez-core-extra-bundle                   v3.0.0            Extra sugar for building eZ Platform websites
mck89/peast                                        v1.10.4           Peast is PHP library that generates AST for JavaScript code
monolog/monolog                                    2.1.1             Sends your logs to files, sockets, inboxes, databases and various web services
myclabs/deep-copy                                  1.10.1            Create deep copies (clones) of your objects
namshi/jose                                        7.2.3             JSON Object Signing and Encryption library for PHP.
nelmio/cors-bundle                                 2.1.0             Adds CORS (Cross-Origin Resource Sharing) headers support in your Symfony application
netgen/ezplatform-search-extra                     2.0.x-dev c8a4dbf Netgen's extra bits for eZ Platform search
netgen/ezplatform-site-api                         4.0.x-dev 18150d2 Netgen's Site API for eZ Platform
netgen/query-translator                            1.0.2             Query Translator is a search query translator with AST representation
netgen/tagsbundle                                  4.0.3             Netgen Tags Bundle is an eZ Platform bundle for taxonomy management and easier classification of content...
nicmart/tree                                       v0.2.7            A basic but flexible php tree data structure and a fluent tree builder implementation.
nikic/php-parser                                   v4.7.0            A PHP parser written in PHP
novactive/ezseobundle                              5.2.0             Novactive eZ SEO Bundle is an eZ Platform bundle for SEO simplications. metas, sitemaps, robots.txt, etc.
ocramius/package-versions                          1.9.0             Composer plugin that provides efficient querying for installed package versions (no runtime IO)
ocramius/proxy-manager                             2.8.1             A library providing utilities to generate, instantiate and generally operate with Object Proxies
ondram/ci-detector                                 2.1.0             Detect current continuous integration server and provide unified access to properties of current build
oneup/flysystem-bundle                             3.5.0             Integrates Flysystem filesystem abstraction library to your Symfony project.
overblog/graphiql-bundle                           v0.2.1            Symfony GraphiQLBundle makes possible to render the UI into your symfony project
overblog/graphql-bundle                            v0.11.19          This bundle provides tools to build a GraphQL server in your Symfony App.
pagerfanta/pagerfanta                              v2.4.1            Pagination for PHP
phar-io/manifest                                   1.0.3             Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                                    2.0.1             Library for handling version information and constraints
php-http/client-common                             2.3.0             Common HTTP Client implementations and tools for HTTPlug
php-http/curl-client                               2.1.0             PSR-18 and HTTPlug Async client with cURL
php-http/discovery                                 1.9.1             Finds installed HTTPlug implementations and PSR-7 message factories
php-http/guzzle6-adapter                           v2.0.1            Guzzle 6 HTTP Adapter
php-http/httplug                                   2.2.0             HTTPlug, the HTTP client abstraction for PHP
php-http/message                                   1.8.0             HTTP Message related tools
php-http/message-factory                           v1.0.2            Factory interfaces for PSR-7 HTTP Message
php-http/promise                                   1.1.0             Promise used for asynchronous HTTP requests
phpdocumentor/reflection-common                    2.2.0             Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock                  5.2.0             With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve i...
phpdocumentor/type-resolver                        1.3.0             A PSR-5 based resolver of Class names, Types and Structural Element Names
phpspec/prophecy                                   1.11.1            Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage                          7.0.10            Library that provides collection, processing, and rendering functionality for PHP code coverage informat...
phpunit/php-file-iterator                          2.0.2             FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template                          1.2.1             Simple template engine.
phpunit/php-timer                                  2.1.2             Utility class for timing
phpunit/php-token-stream                           3.1.1             Wrapper around PHP's tokenizer extension.
phpunit/phpunit                                    8.5.8             The PHP Unit Testing framework.
platformsh/config-reader                           2.3.1             Small helper to access Platform.sh environment variables
platformsh/symfonyflex-bridge                      2.2.0             Bridge library for running Symfony Flex on Platform.sh
psr/cache                                          1.0.1             Common interface for caching libraries
psr/container                                      1.0.0             Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher                               1.0.0             Standard interfaces for event handling.
psr/http-client                                    1.0.1             Common interface for HTTP clients
psr/http-factory                                   1.0.1             Common interfaces for PSR-7 HTTP message factories
psr/http-message                                   1.0.1             Common interface for HTTP messages
psr/link                                           1.0.0             Common interfaces for HTTP links
psr/log                                            1.1.3             Common interface for logging libraries
ralouphie/getallheaders                            3.0.3             A polyfill for getallheaders.
ramsey/uuid                                        3.9.3             Formerly rhumsaa/uuid. A PHP 5.4+ library for generating RFC 4122 version 1, 3, 4, and 5 universally uni...
react/promise                                      v2.8.0            A lightweight implementation of CommonJS Promises/A for PHP
scssphp/scssphp                                    1.1.1             scssphp is a compiler for SCSS written in PHP.
sebastian/code-unit-reverse-lookup                 1.0.1             Looks up which function or method a line of code belongs to
sebastian/comparator                               3.0.2             Provides the functionality to compare PHP values for equality
sebastian/environment                              4.2.3             Provides functionality to handle HHVM/PHP environments
sebastian/exporter                                 3.1.2             Provides the functionality to export PHP variables for visualization
sebastian/global-state                             3.0.0             Snapshotting of global state
sebastian/object-enumerator                        3.0.3             Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector                         1.1.1             Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context                        3.0.0             Provides functionality to recursively process PHP variables
sebastian/resource-operations                      2.0.1             Provides a list of PHP built-in functions that operate on resources
sebastian/type                                     1.1.3             Collection of value objects that represent the types of the PHP type system
sebastian/version                                  2.0.1             Library that helps with managing the version number of Git-hosted PHP projects
sensio/framework-extra-bundle                      v5.5.6            This bundle provides a way to configure your controllers with annotations
sensiolabs/security-checker                        v6.0.3            A security checker for your composer.lock
soundasleep/html2text                              1.1.0             A PHP script to convert HTML into a plain text format
swiftmailer/swiftmailer                            v6.2.3            Swiftmailer, free feature-rich PHP mailer
symfony-cmf/routing                                2.3.2             Extends the Symfony routing component for dynamic routes and chaining several routers
symfony/asset                                      v5.1.3            Symfony Asset Component
symfony/browser-kit                                v5.1.3            Symfony BrowserKit Component
symfony/cache                                      v5.1.3            Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts                            v2.1.3            Generic abstractions related to caching
symfony/config                                     v5.1.3            Symfony Config Component
symfony/console                                    v5.1.3            Symfony Console Component
symfony/css-selector                               v5.1.3            Symfony CssSelector Component
symfony/debug-bundle                               v5.1.3            Symfony DebugBundle
symfony/debug-pack                                 v1.0.8            A debug pack for Symfony projects
symfony/dependency-injection                       v5.1.3            Symfony DependencyInjection Component
symfony/deprecation-contracts                      v2.1.3            A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge                            v5.1.3            Symfony Doctrine Bridge
symfony/dom-crawler                                v5.1.3            Symfony DomCrawler Component
symfony/dotenv                                     v5.1.3            Registers environment variables from a .env file
symfony/error-handler                              v5.1.3            Symfony ErrorHandler Component
symfony/event-dispatcher                           v5.1.3            Symfony EventDispatcher Component
symfony/event-dispatcher-contracts                 v2.1.3            Generic abstractions related to dispatching event
symfony/expression-language                        v5.1.3            Symfony ExpressionLanguage Component
symfony/filesystem                                 v5.1.3            Symfony Filesystem Component
symfony/finder                                     v5.1.3            Symfony Finder Component
symfony/flex                                       v1.9.1            Composer plugin for Symfony
symfony/form                                       v5.1.3            Symfony Form Component
symfony/framework-bundle                           v5.1.3            Symfony FrameworkBundle
symfony/http-client                                v5.1.3            Symfony HttpClient component
symfony/http-client-contracts                      v2.1.3            Generic abstractions related to HTTP clients
symfony/http-foundation                            v5.1.3            Symfony HttpFoundation Component
symfony/http-kernel                                v5.1.3            Symfony HttpKernel Component
symfony/intl                                       v5.1.3            A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/lock                                       v5.1.3            Symfony Lock Component
symfony/maker-bundle                               v1.20.0           Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forg...
symfony/mime                                       v5.1.3            A library to manipulate MIME messages
symfony/monolog-bridge                             v5.1.3            Symfony Monolog Bridge
symfony/monolog-bundle                             v3.5.0            Symfony MonologBundle
symfony/options-resolver                           v5.1.3            Symfony OptionsResolver Component
symfony/orm-pack                                   v1.0.8            A pack for the Doctrine ORM
symfony/phpunit-bridge                             v5.1.3            Symfony PHPUnit Bridge
symfony/polyfill-intl-grapheme                     v1.18.1           Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu                          v1.18.1           Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn                          v1.18.1           Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer                   v1.18.1           Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring                          v1.18.1           Symfony polyfill for the Mbstring extension
symfony/polyfill-php72                             v1.18.1           Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73                             v1.18.1           Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80                             v1.18.1           Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/process                                    v5.1.3            Symfony Process Component
symfony/profiler-pack                              v1.0.4            A pack for the Symfony web profiler
symfony/property-access                            v5.1.3            Symfony PropertyAccess Component
symfony/property-info                              v5.1.3            Symfony Property Info Component
symfony/proxy-manager-bridge                       v5.1.3            Symfony ProxyManager Bridge
symfony/routing                                    v5.1.3            Symfony Routing Component
symfony/security-bundle                            v5.1.3            Symfony SecurityBundle
symfony/security-core                              v5.1.3            Symfony Security Component - Core Library
symfony/security-csrf                              v5.1.3            Symfony Security Component - CSRF Library
symfony/security-guard                             v5.1.3            Symfony Security Component - Guard
symfony/security-http                              v5.1.3            Symfony Security Component - HTTP Integration
symfony/serializer                                 v5.1.3            Symfony Serializer Component
symfony/serializer-pack                            v1.0.3            A pack for the Symfony serializer
symfony/service-contracts                          v2.1.3            Generic abstractions related to writing services
symfony/stopwatch                                  v5.1.3            Symfony Stopwatch Component
symfony/string                                     v5.1.3            Symfony String component
symfony/swiftmailer-bundle                         v3.4.0            Symfony SwiftmailerBundle
symfony/templating                                 v5.1.3            Symfony Templating Component
symfony/test-pack                                  v1.0.6            A pack for functional and end-to-end testing within a Symfony app
symfony/thanks                                     v1.2.9            Encourages sending ⭐ and 💵 to fellow PHP package maintainers (not limited to Symfony components)!
symfony/translation                                v5.1.3            Symfony Translation Component
symfony/translation-contracts                      v2.1.3            Generic abstractions related to translation
symfony/twig-bridge                                v5.1.3            Symfony Twig Bridge
symfony/twig-bundle                                v5.1.3            Symfony TwigBundle
symfony/validator                                  v5.1.3            Symfony Validator Component
symfony/var-dumper                                 v5.1.3            Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter                               v5.1.3            A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-link                                   v5.1.3            Symfony WebLink Component
symfony/web-profiler-bundle                        v5.1.3            Symfony WebProfilerBundle
symfony/webpack-encore-bundle                      v1.7.3            Integration with your Symfony app & Webpack Encore!
symfony/workflow                                   v5.1.3            Symfony Workflow Component
symfony/yaml                                       v5.1.3            Symfony Yaml Component
textalk/websocket                                  1.3.1             WebSocket client and server
theseer/tokenizer                                  1.2.0             A small library for converting tokenized PHP source code into XML and potentially other formats
toflar/psr6-symfony-http-cache-store               2.3.1             An alternative store implementation for Symfony's HttpCache reverse proxy that supports auto-pruning of ...
twig/extra-bundle                                  v3.0.5            A Symfony bundle for extra Twig extensions
twig/intl-extra                                    v3.0.5            A Twig extension for Intl
twig/string-extra                                  v3.0.5            A Twig extension for Symfony String
twig/twig                                          v3.0.5            Twig, the flexible, fast, and secure template language for PHP
webimpress/safe-writer                             2.0.1             Tool to write files safely, to avoid race conditions
webmozart/assert                                   1.9.1             Assertions to validate method input/output with nice error messages.
webonyx/graphql-php                                v0.13.9           A PHP port of GraphQL reference implementation
willdurand/js-translation-bundle                   3.0.1             A pretty nice way to expose your translation messages to your JavaScript.
willdurand/jsonp-callback-validator                v1.1.0            JSONP callback validator.
zetacomponents/base                                1.9.1             The Base package provides the basic infrastructure that all packages rely on. Therefore every component ...
zetacomponents/feed                                1.4               This component handles parsing and creating RSS1, RSS2 and ATOM feeds, with support for different feed m...
zetacomponents/system-information                  1.1.1             Provides access to common system variables, such as CPU type and speed, and the available amount of memory.

**Comment by pspanja** [comment]
I can't find any significant differences, but then again we don't have access to the EE parts. In any case, this fix does not look like it will cause any problems, so I added it to the `4.0` branch in 4bbc6ed45d9b8e6551210fd9f37cbcf849c2bb7f. We can always revisit this later if needed.

**Comment by YohannsMonnier** [comment]
Thank you very much @pspanja

**Pull request closed without merging**
